CREATE TABLE usage_stats (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    datetime TIMESTAMP WITH TIME ZONE NOT NULL,
    selected_language TEXT NOT NULL,
    num_children INTEGER NOT NULL,
    ages TEXT NOT NULL,
    values_to_teach TEXT NOT NULL,
    selected_model TEXT NOT NULL,
    rating TEXT
);

-- Add a comment to the table
COMMENT ON TABLE usage_stats IS 'Stores usage statistics for the Bedtime Story Generator';

-- Add comments to the columns
COMMENT ON COLUMN usage_stats.id IS 'Unique identifier for each usage record';
COMMENT ON COLUMN usage_stats.datetime IS 'Timestamp of when the story was generated';
COMMENT ON COLUMN usage_stats.selected_language IS 'Language selected for the story';
COMMENT ON COLUMN usage_stats.num_children IS 'Number of children the story was generated for';
COMMENT ON COLUMN usage_stats.ages IS 'Comma-separated list of ages of the children';
COMMENT ON COLUMN usage_stats.values_to_teach IS 'Values or lessons to be taught in the story';
COMMENT ON COLUMN usage_stats.selected_model IS 'AI model used to generate the story';
COMMENT ON COLUMN usage_stats.rating IS 'User feedback rating for the generated story';

-- Create an index on the datetime column for faster queries
CREATE INDEX idx_usage_stats_datetime ON usage_stats(datetime);