services:
  - type: web
    name: streamlit-app
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run app.py
    plan: free
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: OPENROUTER_API_KEY
        sync: false
      - key: OPENROUTER_SITE_URL
        sync: false
      - key: OPENROUTER_APP_NAME
        value: Bedtime Storyteller
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_KEY
        sync: false
      - key: DEFAULT_LANGUAGE
        value: English
      - key: MODEL
        sync: false
